# Deploy "Diary" project
version: "3.7"

networks:
  diary_net:
    driver: bridge
    name: diary_net # own network (docker network ls)
    ipam:
      config:
        - subnet: 172.22.0.0/24

services:
  diary-postgres:
    image: postgres:14.8
    hostname: diary-postgres
    container_name: diary-postgres
    restart: always
    ports:
      - 127.0.0.1:35432:5432
    networks:
      - diary_net
    # volumes ?
    environment:
      POSTGRES_PASSWORD: postgres # for default user and database name - "postgres"

  diary-api:
    build: Diary.Api/
    hostname: diary-api
    container_name: diary-api
    depends_on:
      - diary-postgres
    ports:
      - 35000:5000 # fix, default localhost ipv6
    networks:
      - diary_net
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5000 # {scheme1}://{host1}:{port1},..,{schemeX}://{hostX}:{portX}
